# Generated by Django 5.1.6 on 2025-03-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_name', models.CharField(max_length=100)),
                ('registration_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address_line1', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=15)),
                ('landmark', models.CharField(max_length=50)),
                ('facilities', models.JSONField(default=list)),
                ('form_12a', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('form_13a', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
